
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author berkay
 */
public class IlacBot extends javax.swing.JFrame {
    
    ArrayList<String>bot_ilaclar = new ArrayList<String>();
    IlacFiyat ilac_fiyat = new IlacFiyat();
    UserOperations operations = new UserOperations();

    /**
     * Creates new form IlacBot
     */
    public IlacBot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        bas_agrisi = new javax.swing.JCheckBox();
        mide_bulantisi = new javax.swing.JCheckBox();
        karin_agrisi = new javax.swing.JCheckBox();
        ates = new javax.swing.JCheckBox();
        halsizlik = new javax.swing.JCheckBox();
        kusma = new javax.swing.JCheckBox();
        ishal = new javax.swing.JCheckBox();
        burun_akintisi = new javax.swing.JCheckBox();
        hapsurma = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        bot_yazi = new javax.swing.JTextField();
        bogaz_agrisi = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1500, 800));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel1.setText("İLAÇBOT 'A HOŞGELDİNİZ");

        bas_agrisi.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        bas_agrisi.setText("Baş Ağrısı");
        bas_agrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bas_agrisiActionPerformed(evt);
            }
        });

        mide_bulantisi.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        mide_bulantisi.setText("Mide Bulantısı");
        mide_bulantisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mide_bulantisiActionPerformed(evt);
            }
        });

        karin_agrisi.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        karin_agrisi.setText("Karın Ağrısı");
        karin_agrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karin_agrisiActionPerformed(evt);
            }
        });

        ates.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        ates.setText("Ateş");
        ates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atesActionPerformed(evt);
            }
        });

        halsizlik.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        halsizlik.setText("Halsizlik");
        halsizlik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halsizlikActionPerformed(evt);
            }
        });

        kusma.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        kusma.setText("Kusma");
        kusma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kusmaActionPerformed(evt);
            }
        });

        ishal.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        ishal.setText("İshal");
        ishal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ishalActionPerformed(evt);
            }
        });

        burun_akintisi.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        burun_akintisi.setText("Burun Akıntısı");
        burun_akintisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burun_akintisiActionPerformed(evt);
            }
        });

        hapsurma.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        hapsurma.setText("Hapşurma");
        hapsurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapsurmaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel2.setText("Lütfen aşağıdaki seçeneklerden sizin şikayetlerinize uyanları seçiniz.");

        bogaz_agrisi.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        bogaz_agrisi.setText("Boğaz Ağrısı");
        bogaz_agrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bogaz_agrisiActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jButton1.setText("Seçimleri Onayla");
        jButton1.setSize(new java.awt.Dimension(100, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jButton2.setText("Seçimleri Temizle");
        jButton2.setSize(new java.awt.Dimension(100, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jButton3.setText("İlaçları Sepete Ekle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("önceki sayfa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jButton5.setText("Sepete Git");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bas_agrisi)
                                    .addComponent(mide_bulantisi)
                                    .addComponent(karin_agrisi)
                                    .addComponent(ates)
                                    .addComponent(halsizlik))
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(burun_akintisi)
                                    .addComponent(hapsurma)
                                    .addComponent(kusma)
                                    .addComponent(ishal)
                                    .addComponent(bogaz_agrisi))
                                .addGap(238, 238, 238)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(53, 53, 53)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(bot_yazi, javax.swing.GroupLayout.PREFERRED_SIZE, 1418, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bas_agrisi)
                            .addComponent(burun_akintisi))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mide_bulantisi)
                            .addComponent(hapsurma))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kusma)
                            .addComponent(karin_agrisi))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ates)
                            .addComponent(ishal))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bogaz_agrisi)
                            .addComponent(halsizlik))
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(bot_yazi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bas_agrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bas_agrisiActionPerformed
        if(bot_ilaclar.contains("MAJEZİK")){
            return;
        }else{
        bot_ilaclar.add("MAJEZİK");
        }
         
    }//GEN-LAST:event_bas_agrisiActionPerformed

    private void mide_bulantisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mide_bulantisiActionPerformed
          if(bot_ilaclar.contains("EMADUR")){
            return;
        }else{
            bot_ilaclar.add("EMADUR");
        }
    }//GEN-LAST:event_mide_bulantisiActionPerformed

    private void karin_agrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karin_agrisiActionPerformed
         if(bot_ilaclar.contains("DOLOREX")){
            return;
        }else{
        bot_ilaclar.add("DOLOREX");
        }
    }//GEN-LAST:event_karin_agrisiActionPerformed

    private void atesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atesActionPerformed
        if(bot_ilaclar.contains("PAROL")){
            return;
        }else{
        bot_ilaclar.add("PAROL");
        }
    }//GEN-LAST:event_atesActionPerformed

    private void halsizlikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halsizlikActionPerformed
        if(bot_ilaclar.contains("PAROL")){
            return;
        }else{
        bot_ilaclar.add("PAROL");
        }
    }//GEN-LAST:event_halsizlikActionPerformed

    private void kusmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kusmaActionPerformed
        if(bot_ilaclar.contains("EMADUR")){
            return;
        }else{
        bot_ilaclar.add("EMADUR");
        }
    }//GEN-LAST:event_kusmaActionPerformed

    private void ishalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ishalActionPerformed
       if(bot_ilaclar.contains("LOMOTİL")){
            return;
        }else{
        bot_ilaclar.add("LOMOTİL");
        }
    }//GEN-LAST:event_ishalActionPerformed

    private void burun_akintisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burun_akintisiActionPerformed
        if(bot_ilaclar.contains("NUROFEN")){
            return;
        }else{
        bot_ilaclar.add("NUROFEN");
        }
    }//GEN-LAST:event_burun_akintisiActionPerformed

    private void hapsurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapsurmaActionPerformed
        if(bot_ilaclar.contains("NUROFEN")){
            return;
        }else{
        bot_ilaclar.add("NUROFEN");
        }
    }//GEN-LAST:event_hapsurmaActionPerformed

    private void bogaz_agrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bogaz_agrisiActionPerformed
        if(bot_ilaclar.contains("NUROFEN")){
            return;
        }else{
        bot_ilaclar.add("NUROFEN");
        }
    }//GEN-LAST:event_bogaz_agrisiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        bot_yazi.setText("");
        if(bot_ilaclar.isEmpty()){
            bot_yazi.setText("Lütfen rahatıszlıklarınızı seçiniz");
        }else{
        bot_yazi.setText("İlaçlarınız :" + bot_ilaclar);
        
        }
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       bot_ilaclar.clear();
       operations.sepetiTemizle();
       
       IlacBot ilacbot = new IlacBot();
       setVisible(false);
       ilacbot.setVisible(true);
       
       
       
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if(bot_ilaclar.contains("MAJEZİK")) {
           
      String urun_adi = "MAJEZİK AĞRI KESİCİ HAP";
      int urun_adedi = 1;
      double birim_fiyati = 70;
      double toplam_fiyat = urun_adedi*birim_fiyati;
      
      operations.addProduct(urun_adi,urun_adedi,birim_fiyati);
       }
       
        if(bot_ilaclar.contains("NUROFEN")) {
           
      String urun_adi = "NUROFEN GRİP İLACI";
      int urun_adedi = 1;
      double birim_fiyati = 39.99;
      double toplam_fiyat = urun_adedi*birim_fiyati;
      
      operations.addProduct(urun_adi,urun_adedi,birim_fiyati);
       }
        
         if(bot_ilaclar.contains("EMADUR")) {
           
      String urun_adi = "EMADUR MİDE BULANTISI HAPI";
      int urun_adedi = 1;
      double birim_fiyati = 50;
      double toplam_fiyat = urun_adedi*birim_fiyati;
      
      operations.addProduct(urun_adi,urun_adedi,birim_fiyati);
       }
         
          if(bot_ilaclar.contains("DOLOREX")) {
           
      String urun_adi = "DOLOREX KARIN AĞRISI İLACI";
      int urun_adedi = 1;
      double birim_fiyati = 80;
      double toplam_fiyat = urun_adedi*birim_fiyati;
      
      operations.addProduct(urun_adi,urun_adedi,birim_fiyati);
          }
          
           if(bot_ilaclar.contains("LOMOTİL")) {
           
      String urun_adi = "LOMOTİL İSHAL HAPI";
      int urun_adedi = 1;
      double birim_fiyati = 43;
      double toplam_fiyat = urun_adedi*birim_fiyati;
      
      operations.addProduct(urun_adi,urun_adedi,birim_fiyati);
       }
           
            if(bot_ilaclar.contains("PAROL")) {
           
      String urun_adi = "PAROL ATEŞ DÜŞÜRÜCÜ İLAÇ";
      int urun_adedi = 1;
      double birim_fiyati = 29.99;
      double toplam_fiyat = urun_adedi*birim_fiyati;
      
      operations.addProduct(urun_adi,urun_adedi,birim_fiyati);
       }
      
      
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ReceteIlac receteilac = new ReceteIlac();
        setVisible(false);
        receteilac.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         Sepet sepet = new Sepet(this,true);
        setVisible(false);
        sepet.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IlacBot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ates;
    private javax.swing.JCheckBox bas_agrisi;
    private javax.swing.JCheckBox bogaz_agrisi;
    private javax.swing.JTextField bot_yazi;
    private javax.swing.JCheckBox burun_akintisi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JCheckBox halsizlik;
    private javax.swing.JCheckBox hapsurma;
    private javax.swing.JCheckBox ishal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox karin_agrisi;
    private javax.swing.JCheckBox kusma;
    private javax.swing.JCheckBox mide_bulantisi;
    // End of variables declaration//GEN-END:variables
}
